# Generated by Django 4.2 on 2025-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(unique=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("memory", models.CharField(blank=True, max_length=50, null=True)),
                ("manufacturer", models.CharField(blank=True, max_length=200, null=True)),
                ("regular_price", models.CharField(blank=True, max_length=100, null=True)),
                ("sale_price", models.CharField(blank=True, max_length=100, null=True)),
                ("images", models.JSONField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("reviews_count", models.IntegerField(blank=True, null=True)),
                ("screen_size", models.CharField(blank=True, max_length=50, null=True)),
                ("resolution", models.CharField(blank=True, max_length=50, null=True)),
                ("specifications", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
