# Generated by Django 4.2 on 2025-11-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="regular_price",
            new_name="new_price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="sale_price",
            new_name="old_price",
        ),
        migrations.AddField(
            model_name="product",
            name="is_discount",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
